//@ts-nocheck
// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export function gql(strings: TemplateStringsArray, ...args: string[]): string {
  let str = ''
  strings.forEach((string, i) => {
    str += string + (args[i] || '')
  })
  return str
}
export type Maybe<T> = T | null
export type InputMaybe<T> = Maybe<T>
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> }
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> }
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = {
  [_ in K]?: never
}
export type Incremental<T> =
  | T
  | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never }
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string }
  String: { input: string; output: string }
  Boolean: { input: boolean; output: boolean }
  Int: { input: number; output: number }
  Float: { input: number; output: number }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any }
  JSON: { input: any; output: any }
}

export type SystemInfo = {
  __typename?: 'SystemInfo'
  filename: Scalars['String']['output']
  title?: Maybe<Scalars['String']['output']>
  basename: Scalars['String']['output']
  hasReferences?: Maybe<Scalars['Boolean']['output']>
  breadcrumbs: Array<Scalars['String']['output']>
  path: Scalars['String']['output']
  relativePath: Scalars['String']['output']
  extension: Scalars['String']['output']
  template: Scalars['String']['output']
  collection: Collection
}

export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>
}

export type Folder = {
  __typename?: 'Folder'
  name: Scalars['String']['output']
  path: Scalars['String']['output']
}

export type PageInfo = {
  __typename?: 'PageInfo'
  hasPreviousPage: Scalars['Boolean']['output']
  hasNextPage: Scalars['Boolean']['output']
  startCursor: Scalars['String']['output']
  endCursor: Scalars['String']['output']
}

export type Node = {
  id: Scalars['ID']['output']
}

export type Document = {
  id: Scalars['ID']['output']
  _sys?: Maybe<SystemInfo>
  _values: Scalars['JSON']['output']
}

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output']
  pageInfo: PageInfo
}

export type Query = {
  __typename?: 'Query'
  getOptimizedQuery?: Maybe<Scalars['String']['output']>
  collection: Collection
  collections: Array<Collection>
  node: Node
  document: DocumentNode
  product: Product
  productConnection: ProductConnection
  category: Category
  categoryConnection: CategoryConnection
  review: Review
  reviewConnection: ReviewConnection
}

export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input']
}

export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>
}

export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>
}

export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>
  relativePath?: InputMaybe<Scalars['String']['input']>
}

export type QueryProductArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>
}

export type QueryProductConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>
  after?: InputMaybe<Scalars['String']['input']>
  first?: InputMaybe<Scalars['Float']['input']>
  last?: InputMaybe<Scalars['Float']['input']>
  sort?: InputMaybe<Scalars['String']['input']>
  filter?: InputMaybe<ProductFilter>
}

export type QueryCategoryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>
}

export type QueryCategoryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>
  after?: InputMaybe<Scalars['String']['input']>
  first?: InputMaybe<Scalars['Float']['input']>
  last?: InputMaybe<Scalars['Float']['input']>
  sort?: InputMaybe<Scalars['String']['input']>
  filter?: InputMaybe<CategoryFilter>
}

export type QueryReviewArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>
}

export type QueryReviewConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>
  after?: InputMaybe<Scalars['String']['input']>
  first?: InputMaybe<Scalars['Float']['input']>
  last?: InputMaybe<Scalars['Float']['input']>
  sort?: InputMaybe<Scalars['String']['input']>
  filter?: InputMaybe<ReviewFilter>
}

export type DocumentFilter = {
  product?: InputMaybe<ProductFilter>
  category?: InputMaybe<CategoryFilter>
  review?: InputMaybe<ReviewFilter>
}

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges'
  cursor: Scalars['String']['output']
  node?: Maybe<DocumentNode>
}

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection'
  pageInfo: PageInfo
  totalCount: Scalars['Float']['output']
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>
}

export type Collection = {
  __typename?: 'Collection'
  name: Scalars['String']['output']
  slug: Scalars['String']['output']
  label?: Maybe<Scalars['String']['output']>
  path: Scalars['String']['output']
  format?: Maybe<Scalars['String']['output']>
  matches?: Maybe<Scalars['String']['output']>
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>
  documents: DocumentConnection
}

export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>
  after?: InputMaybe<Scalars['String']['input']>
  first?: InputMaybe<Scalars['Float']['input']>
  last?: InputMaybe<Scalars['Float']['input']>
  sort?: InputMaybe<Scalars['String']['input']>
  filter?: InputMaybe<DocumentFilter>
  folder?: InputMaybe<Scalars['String']['input']>
}

export type DocumentNode = Product | Category | Review | Folder

export type ProductImages = {
  __typename?: 'ProductImages'
  main: Scalars['String']['output']
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>
}

export type ProductSizes = {
  __typename?: 'ProductSizes'
  size: Scalars['String']['output']
  stock: Scalars['Float']['output']
}

export type ProductPatches = {
  __typename?: 'ProductPatches'
  id: Scalars['String']['output']
  name: Scalars['String']['output']
  price: Scalars['Float']['output']
  image?: Maybe<Scalars['String']['output']>
}

export type Product = Node &
  Document & {
    __typename?: 'Product'
    name: Scalars['String']['output']
    slug: Scalars['String']['output']
    description: Scalars['String']['output']
    productType: Scalars['String']['output']
    basePrice: Scalars['Float']['output']
    category: Scalars['String']['output']
    competition?: Maybe<Scalars['String']['output']>
    club?: Maybe<Scalars['String']['output']>
    season?: Maybe<Scalars['String']['output']>
    images?: Maybe<ProductImages>
    sizes?: Maybe<Array<Maybe<ProductSizes>>>
    allowCustomization?: Maybe<Scalars['Boolean']['output']>
    customizationPrice?: Maybe<Scalars['Float']['output']>
    patches?: Maybe<Array<Maybe<ProductPatches>>>
    featured?: Maybe<Scalars['Boolean']['output']>
    published?: Maybe<Scalars['Boolean']['output']>
    createdAt?: Maybe<Scalars['String']['output']>
    id: Scalars['ID']['output']
    _sys: SystemInfo
    _values: Scalars['JSON']['output']
  }

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>
  eq?: InputMaybe<Scalars['String']['input']>
  exists?: InputMaybe<Scalars['Boolean']['input']>
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>
}

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>
  lte?: InputMaybe<Scalars['Float']['input']>
  gte?: InputMaybe<Scalars['Float']['input']>
  gt?: InputMaybe<Scalars['Float']['input']>
  eq?: InputMaybe<Scalars['Float']['input']>
  exists?: InputMaybe<Scalars['Boolean']['input']>
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>
}

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>
  eq?: InputMaybe<Scalars['String']['input']>
  exists?: InputMaybe<Scalars['Boolean']['input']>
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>
}

export type ProductImagesFilter = {
  main?: InputMaybe<ImageFilter>
  gallery?: InputMaybe<ImageFilter>
}

export type ProductSizesFilter = {
  size?: InputMaybe<StringFilter>
  stock?: InputMaybe<NumberFilter>
}

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>
  exists?: InputMaybe<Scalars['Boolean']['input']>
}

export type ProductPatchesFilter = {
  id?: InputMaybe<StringFilter>
  name?: InputMaybe<StringFilter>
  price?: InputMaybe<NumberFilter>
  image?: InputMaybe<ImageFilter>
}

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>
  before?: InputMaybe<Scalars['String']['input']>
  eq?: InputMaybe<Scalars['String']['input']>
  exists?: InputMaybe<Scalars['Boolean']['input']>
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>
}

export type ProductFilter = {
  name?: InputMaybe<StringFilter>
  slug?: InputMaybe<StringFilter>
  description?: InputMaybe<StringFilter>
  productType?: InputMaybe<StringFilter>
  basePrice?: InputMaybe<NumberFilter>
  category?: InputMaybe<StringFilter>
  competition?: InputMaybe<StringFilter>
  club?: InputMaybe<StringFilter>
  season?: InputMaybe<StringFilter>
  images?: InputMaybe<ProductImagesFilter>
  sizes?: InputMaybe<ProductSizesFilter>
  allowCustomization?: InputMaybe<BooleanFilter>
  customizationPrice?: InputMaybe<NumberFilter>
  patches?: InputMaybe<ProductPatchesFilter>
  featured?: InputMaybe<BooleanFilter>
  published?: InputMaybe<BooleanFilter>
  createdAt?: InputMaybe<DatetimeFilter>
}

export type ProductConnectionEdges = {
  __typename?: 'ProductConnectionEdges'
  cursor: Scalars['String']['output']
  node?: Maybe<Product>
}

export type ProductConnection = Connection & {
  __typename?: 'ProductConnection'
  pageInfo: PageInfo
  totalCount: Scalars['Float']['output']
  edges?: Maybe<Array<Maybe<ProductConnectionEdges>>>
}

export type Category = Node &
  Document & {
    __typename?: 'Category'
    name: Scalars['String']['output']
    slug: Scalars['String']['output']
    description?: Maybe<Scalars['String']['output']>
    image?: Maybe<Scalars['String']['output']>
    order?: Maybe<Scalars['Float']['output']>
    id: Scalars['ID']['output']
    _sys: SystemInfo
    _values: Scalars['JSON']['output']
  }

export type CategoryFilter = {
  name?: InputMaybe<StringFilter>
  slug?: InputMaybe<StringFilter>
  description?: InputMaybe<StringFilter>
  image?: InputMaybe<ImageFilter>
  order?: InputMaybe<NumberFilter>
}

export type CategoryConnectionEdges = {
  __typename?: 'CategoryConnectionEdges'
  cursor: Scalars['String']['output']
  node?: Maybe<Category>
}

export type CategoryConnection = Connection & {
  __typename?: 'CategoryConnection'
  pageInfo: PageInfo
  totalCount: Scalars['Float']['output']
  edges?: Maybe<Array<Maybe<CategoryConnectionEdges>>>
}

export type Review = Node &
  Document & {
    __typename?: 'Review'
    author: Scalars['String']['output']
    rating: Scalars['Float']['output']
    content: Scalars['String']['output']
    productSlug: Scalars['String']['output']
    status: Scalars['String']['output']
    createdAt: Scalars['String']['output']
    email?: Maybe<Scalars['String']['output']>
    id: Scalars['ID']['output']
    _sys: SystemInfo
    _values: Scalars['JSON']['output']
  }

export type ReviewFilter = {
  author?: InputMaybe<StringFilter>
  rating?: InputMaybe<NumberFilter>
  content?: InputMaybe<StringFilter>
  productSlug?: InputMaybe<StringFilter>
  status?: InputMaybe<StringFilter>
  createdAt?: InputMaybe<DatetimeFilter>
  email?: InputMaybe<StringFilter>
}

export type ReviewConnectionEdges = {
  __typename?: 'ReviewConnectionEdges'
  cursor: Scalars['String']['output']
  node?: Maybe<Review>
}

export type ReviewConnection = Connection & {
  __typename?: 'ReviewConnection'
  pageInfo: PageInfo
  totalCount: Scalars['Float']['output']
  edges?: Maybe<Array<Maybe<ReviewConnectionEdges>>>
}

export type Mutation = {
  __typename?: 'Mutation'
  addPendingDocument: DocumentNode
  updateDocument: DocumentNode
  deleteDocument: DocumentNode
  createDocument: DocumentNode
  createFolder: DocumentNode
  updateProduct: Product
  createProduct: Product
  updateCategory: Category
  createCategory: Category
  updateReview: Review
  createReview: Review
}

export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input']
  relativePath: Scalars['String']['input']
  template?: InputMaybe<Scalars['String']['input']>
}

export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>
  relativePath: Scalars['String']['input']
  params: DocumentUpdateMutation
}

export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>
  relativePath: Scalars['String']['input']
}

export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>
  relativePath: Scalars['String']['input']
  params: DocumentMutation
}

export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>
  relativePath: Scalars['String']['input']
}

export type MutationUpdateProductArgs = {
  relativePath: Scalars['String']['input']
  params: ProductMutation
}

export type MutationCreateProductArgs = {
  relativePath: Scalars['String']['input']
  params: ProductMutation
}

export type MutationUpdateCategoryArgs = {
  relativePath: Scalars['String']['input']
  params: CategoryMutation
}

export type MutationCreateCategoryArgs = {
  relativePath: Scalars['String']['input']
  params: CategoryMutation
}

export type MutationUpdateReviewArgs = {
  relativePath: Scalars['String']['input']
  params: ReviewMutation
}

export type MutationCreateReviewArgs = {
  relativePath: Scalars['String']['input']
  params: ReviewMutation
}

export type DocumentUpdateMutation = {
  product?: InputMaybe<ProductMutation>
  category?: InputMaybe<CategoryMutation>
  review?: InputMaybe<ReviewMutation>
  relativePath?: InputMaybe<Scalars['String']['input']>
}

export type DocumentMutation = {
  product?: InputMaybe<ProductMutation>
  category?: InputMaybe<CategoryMutation>
  review?: InputMaybe<ReviewMutation>
}

export type ProductImagesMutation = {
  main?: InputMaybe<Scalars['String']['input']>
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>
}

export type ProductSizesMutation = {
  size?: InputMaybe<Scalars['String']['input']>
  stock?: InputMaybe<Scalars['Float']['input']>
}

export type ProductPatchesMutation = {
  id?: InputMaybe<Scalars['String']['input']>
  name?: InputMaybe<Scalars['String']['input']>
  price?: InputMaybe<Scalars['Float']['input']>
  image?: InputMaybe<Scalars['String']['input']>
}

export type ProductMutation = {
  name?: InputMaybe<Scalars['String']['input']>
  slug?: InputMaybe<Scalars['String']['input']>
  description?: InputMaybe<Scalars['String']['input']>
  productType?: InputMaybe<Scalars['String']['input']>
  basePrice?: InputMaybe<Scalars['Float']['input']>
  category?: InputMaybe<Scalars['String']['input']>
  competition?: InputMaybe<Scalars['String']['input']>
  club?: InputMaybe<Scalars['String']['input']>
  season?: InputMaybe<Scalars['String']['input']>
  images?: InputMaybe<ProductImagesMutation>
  sizes?: InputMaybe<Array<InputMaybe<ProductSizesMutation>>>
  allowCustomization?: InputMaybe<Scalars['Boolean']['input']>
  customizationPrice?: InputMaybe<Scalars['Float']['input']>
  patches?: InputMaybe<Array<InputMaybe<ProductPatchesMutation>>>
  featured?: InputMaybe<Scalars['Boolean']['input']>
  published?: InputMaybe<Scalars['Boolean']['input']>
  createdAt?: InputMaybe<Scalars['String']['input']>
}

export type CategoryMutation = {
  name?: InputMaybe<Scalars['String']['input']>
  slug?: InputMaybe<Scalars['String']['input']>
  description?: InputMaybe<Scalars['String']['input']>
  image?: InputMaybe<Scalars['String']['input']>
  order?: InputMaybe<Scalars['Float']['input']>
}

export type ReviewMutation = {
  author?: InputMaybe<Scalars['String']['input']>
  rating?: InputMaybe<Scalars['Float']['input']>
  content?: InputMaybe<Scalars['String']['input']>
  productSlug?: InputMaybe<Scalars['String']['input']>
  status?: InputMaybe<Scalars['String']['input']>
  createdAt?: InputMaybe<Scalars['String']['input']>
  email?: InputMaybe<Scalars['String']['input']>
}

export type ProductPartsFragment = {
  __typename: 'Product'
  name: string
  slug: string
  description: string
  productType: string
  basePrice: number
  category: string
  competition?: string | null
  club?: string | null
  season?: string | null
  allowCustomization?: boolean | null
  customizationPrice?: number | null
  featured?: boolean | null
  published?: boolean | null
  createdAt?: string | null
  images?: {
    __typename: 'ProductImages'
    main: string
    gallery?: Array<string | null> | null
  } | null
  sizes?: Array<{ __typename: 'ProductSizes'; size: string; stock: number } | null> | null
  patches?: Array<{
    __typename: 'ProductPatches'
    id: string
    name: string
    price: number
    image?: string | null
  } | null> | null
}

export type CategoryPartsFragment = {
  __typename: 'Category'
  name: string
  slug: string
  description?: string | null
  image?: string | null
  order?: number | null
}

export type ReviewPartsFragment = {
  __typename: 'Review'
  author: string
  rating: number
  content: string
  productSlug: string
  status: string
  createdAt: string
  email?: string | null
}

export type ProductQueryVariables = Exact<{
  relativePath: Scalars['String']['input']
}>

export type ProductQuery = {
  __typename?: 'Query'
  product: {
    __typename: 'Product'
    id: string
    name: string
    slug: string
    description: string
    productType: string
    basePrice: number
    category: string
    competition?: string | null
    club?: string | null
    season?: string | null
    allowCustomization?: boolean | null
    customizationPrice?: number | null
    featured?: boolean | null
    published?: boolean | null
    createdAt?: string | null
    _sys: {
      __typename?: 'SystemInfo'
      filename: string
      basename: string
      hasReferences?: boolean | null
      breadcrumbs: Array<string>
      path: string
      relativePath: string
      extension: string
    }
    images?: {
      __typename: 'ProductImages'
      main: string
      gallery?: Array<string | null> | null
    } | null
    sizes?: Array<{ __typename: 'ProductSizes'; size: string; stock: number } | null> | null
    patches?: Array<{
      __typename: 'ProductPatches'
      id: string
      name: string
      price: number
      image?: string | null
    } | null> | null
  }
}

export type ProductConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>
  after?: InputMaybe<Scalars['String']['input']>
  first?: InputMaybe<Scalars['Float']['input']>
  last?: InputMaybe<Scalars['Float']['input']>
  sort?: InputMaybe<Scalars['String']['input']>
  filter?: InputMaybe<ProductFilter>
}>

export type ProductConnectionQuery = {
  __typename?: 'Query'
  productConnection: {
    __typename?: 'ProductConnection'
    totalCount: number
    pageInfo: {
      __typename?: 'PageInfo'
      hasPreviousPage: boolean
      hasNextPage: boolean
      startCursor: string
      endCursor: string
    }
    edges?: Array<{
      __typename?: 'ProductConnectionEdges'
      cursor: string
      node?: {
        __typename: 'Product'
        id: string
        name: string
        slug: string
        description: string
        productType: string
        basePrice: number
        category: string
        competition?: string | null
        club?: string | null
        season?: string | null
        allowCustomization?: boolean | null
        customizationPrice?: number | null
        featured?: boolean | null
        published?: boolean | null
        createdAt?: string | null
        _sys: {
          __typename?: 'SystemInfo'
          filename: string
          basename: string
          hasReferences?: boolean | null
          breadcrumbs: Array<string>
          path: string
          relativePath: string
          extension: string
        }
        images?: {
          __typename: 'ProductImages'
          main: string
          gallery?: Array<string | null> | null
        } | null
        sizes?: Array<{ __typename: 'ProductSizes'; size: string; stock: number } | null> | null
        patches?: Array<{
          __typename: 'ProductPatches'
          id: string
          name: string
          price: number
          image?: string | null
        } | null> | null
      } | null
    } | null> | null
  }
}

export type CategoryQueryVariables = Exact<{
  relativePath: Scalars['String']['input']
}>

export type CategoryQuery = {
  __typename?: 'Query'
  category: {
    __typename: 'Category'
    id: string
    name: string
    slug: string
    description?: string | null
    image?: string | null
    order?: number | null
    _sys: {
      __typename?: 'SystemInfo'
      filename: string
      basename: string
      hasReferences?: boolean | null
      breadcrumbs: Array<string>
      path: string
      relativePath: string
      extension: string
    }
  }
}

export type CategoryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>
  after?: InputMaybe<Scalars['String']['input']>
  first?: InputMaybe<Scalars['Float']['input']>
  last?: InputMaybe<Scalars['Float']['input']>
  sort?: InputMaybe<Scalars['String']['input']>
  filter?: InputMaybe<CategoryFilter>
}>

export type CategoryConnectionQuery = {
  __typename?: 'Query'
  categoryConnection: {
    __typename?: 'CategoryConnection'
    totalCount: number
    pageInfo: {
      __typename?: 'PageInfo'
      hasPreviousPage: boolean
      hasNextPage: boolean
      startCursor: string
      endCursor: string
    }
    edges?: Array<{
      __typename?: 'CategoryConnectionEdges'
      cursor: string
      node?: {
        __typename: 'Category'
        id: string
        name: string
        slug: string
        description?: string | null
        image?: string | null
        order?: number | null
        _sys: {
          __typename?: 'SystemInfo'
          filename: string
          basename: string
          hasReferences?: boolean | null
          breadcrumbs: Array<string>
          path: string
          relativePath: string
          extension: string
        }
      } | null
    } | null> | null
  }
}

export type ReviewQueryVariables = Exact<{
  relativePath: Scalars['String']['input']
}>

export type ReviewQuery = {
  __typename?: 'Query'
  review: {
    __typename: 'Review'
    id: string
    author: string
    rating: number
    content: string
    productSlug: string
    status: string
    createdAt: string
    email?: string | null
    _sys: {
      __typename?: 'SystemInfo'
      filename: string
      basename: string
      hasReferences?: boolean | null
      breadcrumbs: Array<string>
      path: string
      relativePath: string
      extension: string
    }
  }
}

export type ReviewConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>
  after?: InputMaybe<Scalars['String']['input']>
  first?: InputMaybe<Scalars['Float']['input']>
  last?: InputMaybe<Scalars['Float']['input']>
  sort?: InputMaybe<Scalars['String']['input']>
  filter?: InputMaybe<ReviewFilter>
}>

export type ReviewConnectionQuery = {
  __typename?: 'Query'
  reviewConnection: {
    __typename?: 'ReviewConnection'
    totalCount: number
    pageInfo: {
      __typename?: 'PageInfo'
      hasPreviousPage: boolean
      hasNextPage: boolean
      startCursor: string
      endCursor: string
    }
    edges?: Array<{
      __typename?: 'ReviewConnectionEdges'
      cursor: string
      node?: {
        __typename: 'Review'
        id: string
        author: string
        rating: number
        content: string
        productSlug: string
        status: string
        createdAt: string
        email?: string | null
        _sys: {
          __typename?: 'SystemInfo'
          filename: string
          basename: string
          hasReferences?: boolean | null
          breadcrumbs: Array<string>
          path: string
          relativePath: string
          extension: string
        }
      } | null
    } | null> | null
  }
}

export const ProductPartsFragmentDoc = gql`
  fragment ProductParts on Product {
    __typename
    name
    slug
    description
    productType
    basePrice
    category
    competition
    club
    season
    images {
      __typename
      main
      gallery
    }
    sizes {
      __typename
      size
      stock
    }
    allowCustomization
    customizationPrice
    patches {
      __typename
      id
      name
      price
      image
    }
    featured
    published
    createdAt
  }
`
export const CategoryPartsFragmentDoc = gql`
  fragment CategoryParts on Category {
    __typename
    name
    slug
    description
    image
    order
  }
`
export const ReviewPartsFragmentDoc = gql`
  fragment ReviewParts on Review {
    __typename
    author
    rating
    content
    productSlug
    status
    createdAt
    email
  }
`
export const ProductDocument = gql`
  query product($relativePath: String!) {
    product(relativePath: $relativePath) {
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
      ...ProductParts
    }
  }
  ${ProductPartsFragmentDoc}
`
export const ProductConnectionDocument = gql`
  query productConnection(
    $before: String
    $after: String
    $first: Float
    $last: Float
    $sort: String
    $filter: ProductFilter
  ) {
    productConnection(
      before: $before
      after: $after
      first: $first
      last: $last
      sort: $sort
      filter: $filter
    ) {
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
      totalCount
      edges {
        cursor
        node {
          ... on Document {
            _sys {
              filename
              basename
              hasReferences
              breadcrumbs
              path
              relativePath
              extension
            }
            id
          }
          ...ProductParts
        }
      }
    }
  }
  ${ProductPartsFragmentDoc}
`
export const CategoryDocument = gql`
  query category($relativePath: String!) {
    category(relativePath: $relativePath) {
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
      ...CategoryParts
    }
  }
  ${CategoryPartsFragmentDoc}
`
export const CategoryConnectionDocument = gql`
  query categoryConnection(
    $before: String
    $after: String
    $first: Float
    $last: Float
    $sort: String
    $filter: CategoryFilter
  ) {
    categoryConnection(
      before: $before
      after: $after
      first: $first
      last: $last
      sort: $sort
      filter: $filter
    ) {
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
      totalCount
      edges {
        cursor
        node {
          ... on Document {
            _sys {
              filename
              basename
              hasReferences
              breadcrumbs
              path
              relativePath
              extension
            }
            id
          }
          ...CategoryParts
        }
      }
    }
  }
  ${CategoryPartsFragmentDoc}
`
export const ReviewDocument = gql`
  query review($relativePath: String!) {
    review(relativePath: $relativePath) {
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
      ...ReviewParts
    }
  }
  ${ReviewPartsFragmentDoc}
`
export const ReviewConnectionDocument = gql`
  query reviewConnection(
    $before: String
    $after: String
    $first: Float
    $last: Float
    $sort: String
    $filter: ReviewFilter
  ) {
    reviewConnection(
      before: $before
      after: $after
      first: $first
      last: $last
      sort: $sort
      filter: $filter
    ) {
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
      totalCount
      edges {
        cursor
        node {
          ... on Document {
            _sys {
              filename
              basename
              hasReferences
              breadcrumbs
              path
              relativePath
              extension
            }
            id
          }
          ...ReviewParts
        }
      }
    }
  }
  ${ReviewPartsFragmentDoc}
`
export type Requester<C = {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
export function getSdk<C>(requester: Requester<C>) {
  return {
    product(
      variables: ProductQueryVariables,
      options?: C
    ): Promise<{
      data: ProductQuery
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[]
      variables: ProductQueryVariables
      query: string
    }> {
      return requester<
        {
          data: ProductQuery
          errors?: {
            message: string
            locations: { line: number; column: number }[]
            path: string[]
          }[]
          variables: ProductQueryVariables
          query: string
        },
        ProductQueryVariables
      >(ProductDocument, variables, options)
    },
    productConnection(
      variables?: ProductConnectionQueryVariables,
      options?: C
    ): Promise<{
      data: ProductConnectionQuery
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[]
      variables: ProductConnectionQueryVariables
      query: string
    }> {
      return requester<
        {
          data: ProductConnectionQuery
          errors?: {
            message: string
            locations: { line: number; column: number }[]
            path: string[]
          }[]
          variables: ProductConnectionQueryVariables
          query: string
        },
        ProductConnectionQueryVariables
      >(ProductConnectionDocument, variables, options)
    },
    category(
      variables: CategoryQueryVariables,
      options?: C
    ): Promise<{
      data: CategoryQuery
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[]
      variables: CategoryQueryVariables
      query: string
    }> {
      return requester<
        {
          data: CategoryQuery
          errors?: {
            message: string
            locations: { line: number; column: number }[]
            path: string[]
          }[]
          variables: CategoryQueryVariables
          query: string
        },
        CategoryQueryVariables
      >(CategoryDocument, variables, options)
    },
    categoryConnection(
      variables?: CategoryConnectionQueryVariables,
      options?: C
    ): Promise<{
      data: CategoryConnectionQuery
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[]
      variables: CategoryConnectionQueryVariables
      query: string
    }> {
      return requester<
        {
          data: CategoryConnectionQuery
          errors?: {
            message: string
            locations: { line: number; column: number }[]
            path: string[]
          }[]
          variables: CategoryConnectionQueryVariables
          query: string
        },
        CategoryConnectionQueryVariables
      >(CategoryConnectionDocument, variables, options)
    },
    review(
      variables: ReviewQueryVariables,
      options?: C
    ): Promise<{
      data: ReviewQuery
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[]
      variables: ReviewQueryVariables
      query: string
    }> {
      return requester<
        {
          data: ReviewQuery
          errors?: {
            message: string
            locations: { line: number; column: number }[]
            path: string[]
          }[]
          variables: ReviewQueryVariables
          query: string
        },
        ReviewQueryVariables
      >(ReviewDocument, variables, options)
    },
    reviewConnection(
      variables?: ReviewConnectionQueryVariables,
      options?: C
    ): Promise<{
      data: ReviewConnectionQuery
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[]
      variables: ReviewConnectionQueryVariables
      query: string
    }> {
      return requester<
        {
          data: ReviewConnectionQuery
          errors?: {
            message: string
            locations: { line: number; column: number }[]
            path: string[]
          }[]
          variables: ReviewConnectionQueryVariables
          query: string
        },
        ReviewConnectionQueryVariables
      >(ReviewConnectionDocument, variables, options)
    },
  }
}
export type Sdk = ReturnType<typeof getSdk>

// TinaSDK generated code
import { createClient, TinaClient } from 'tinacms/dist/client'

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request(
      {
        query: doc,
        variables: vars,
        url,
      },
      options
    )

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: 'http://localhost:4001/graphql',
        queries,
      })
    )
  )

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}
